# Generated by Django 5.0.6 on 2024-07-10 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type_of_service', models.CharField(max_length=100)),
                ('service_provider', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='autobot_app.car')),
            ],
        ),
    ]
